<?php

define('ZBX_PAGE_NO_HEADER', 1);
define('ZBX_PAGE_NO_FOOTER', 1);
define('ZBX_PAGE_NO_MENU', true);

require_once dirname(__FILE__).'/../page_header.php';

global $ZBX_SERVER_NAME;

$sessionid = $data['sessionid'];
$name = $data['name'];

$error = $data['error'];

(new CDiv([
	(new CTag('main', true, [
		(isset($ZBX_SERVER_NAME) && $ZBX_SERVER_NAME !== '')
			? (new CDiv($ZBX_SERVER_NAME))->addClass(ZBX_STYLE_SERVER_NAME)
			: null,
		(new CDiv([
			(new CDiv(makeLogo(LOGO_TYPE_NORMAL)))->addClass(ZBX_STYLE_SIGNIN_LOGO),
			(new CForm())
				->setId('ggl_form')
				->cleanItems()
				->addVar('name', $name, 'name')
				->addVar('sessionid', $sessionid, 'sessionid')
				->addItem(
					isset($data['qr_url'])
					? (new CList())
					->addItem([
						(new CLabel( 'Scan this QR code in Google Authenticator app on your device to enroll in 2FA:', 'qr_label'))
							->addStyle('text-align:center;padding-bottom:10px'),
						(new CImg($data['qr_url'], 'ga_qr'))
							->addStyle('display: block;margin-left: auto;margin-right: auto;')
					])
					: null
				)
				->addItem(
					(new CList())
						->addItem([
							(new CLabel( 'Enter 6-digit code generated by Google Authenticator app on your device to complete authentication:', 'code'))
								->addStyle('text-align:center;padding-bottom:10px'),
							(new CDiv([
								(new CTextBox('code'))
									->setAttribute('autofocus', 'autofocus')
									->setAttribute('maxlength', '6')
									->addStyle('text-align:center;width:100px')
							]))->addStyle('text-align:center;'),
							(new CDiv($error))->addClass(ZBX_STYLE_RED)->addStyle('text-align:center;')
						])
						->addItem(new CSubmit('enter', _('Sign in')))
				)
		]))->addClass(ZBX_STYLE_SIGNIN_CONTAINER),
		(new CDiv([
			(new CLink(_('Help'), CBrandHelper::getHelpUrl()))
				->setTarget('_blank')
				->addClass(ZBX_STYLE_GREY)
				->addClass(ZBX_STYLE_LINK_ALT),
			CBrandHelper::isRebranded() ? null : '&nbsp;&nbsp;•&nbsp;&nbsp;',
			CBrandHelper::isRebranded()
				? null
				: (new CLink(_('Support'), getSupportUrl()))
					->setTarget('_blank')
					->addClass(ZBX_STYLE_GREY)
					->addClass(ZBX_STYLE_LINK_ALT)
		]))->addClass(ZBX_STYLE_SIGNIN_LINKS)
	])),
	makePageFooter(false)
]))
	->addClass(ZBX_STYLE_LAYOUT_WRAPPER)
	->show();
?>
</body>
